version: "3"

services:

  runtime-setup:
    image: netty-tcnative-opensuse:default
    build:
      context: ../
      dockerfile: docker/Dockerfile.opensuse

  common: &common
    image: netty-tcnative-opensuse:default
    depends_on: [runtime-setup]
    environment:
      - GPG_KEYNAME
      - GPG_PASSPHRASE
      - GPG_PRIVATE_KEY
      - MAVEN_OPTS
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2/repository:/root/.m2/repository
      - ..:/code
    working_dir: /code

  build:
    <<: *common
    command: /bin/bash -cl "./mvnw clean package"

  shell:
    <<: *common
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.gnupg:/root/.gnupg
      - ~/.m2:/root/.m2
      - ~/.gitconfig:/root/.gitconfig
      - ~/.gitignore:/root/.gitignore
      - ..:/code
    entrypoint: /bin/bash
