FROM debian:7
MAINTAINER netty@googlegroups.com
ENTRYPOINT /bin/bash

ENV SOURCE_DIR $HOME/source
ENV MAVEN_VERSION 3.5.0
ENV JAVA_VERSION 7
ENV CMAKE_VERSION 3.8.2
ENV NINJA_VERSION 1.7.2
ENV GO_VERSION 1.9.3
ENV GCC_VERSION 4.9.4

RUN apt-get -y update && apt-get -y install \
 autoconf \
 automake \
 bzip2 \
 cmake \
 gcc \
 gcc-multilib \
 git \
 gnupg \
 g++ \
 libapr1-dev \
 libssl-dev \
 libtool \
 make \
 openjdk-$JAVA_VERSION-jdk \
 perl \
 tar \
 unzip \
 wget \
 xutils-dev \
 zip

RUN mkdir $SOURCE_DIR
WORKDIR $SOURCE_DIR

RUN wget -q https://cmake.org/files/v3.8/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz && tar zxf cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz && mv cmake-$CMAKE_VERSION-Linux-x86_64 /opt/ && echo 'PATH=/opt/cmake-$CMAKE_VERSION-Linux-x86_64/bin:$PATH' >> ~/.bashrc

RUN wget -q https://github.com/ninja-build/ninja/releases/download/v$NINJA_VERSION/ninja-linux.zip && unzip ninja-linux.zip && mkdir -p /opt/ninja-$NINJA_VERSION/bin && mv ninja /opt/ninja-$NINJA_VERSION/bin && echo 'PATH=/opt/ninja-$NINJA_VERSION/bin:$PATH' >> ~/.bashrc

RUN wget -q http://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz && tar zxf go$GO_VERSION.linux-amd64.tar.gz && mv go /opt/ && echo 'PATH=/opt/go/bin:$PATH' >> ~/.bashrc && echo 'export GOROOT=/opt/go/' >> ~/.bashrc

RUN wget -q http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && tar zxf apache-maven-$MAVEN_VERSION-bin.tar.gz && mv apache-maven-$MAVEN_VERSION /opt/ && echo 'PATH=/opt/apache-maven-$MAVEN_VERSION/bin:$PATH' >> ~/.bashrc

RUN wget -q ftp://ftp.gnu.org/gnu/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz && tar zxf gcc-$GCC_VERSION.tar.gz
WORKDIR gcc-$GCC_VERSION

RUN ./contrib/download_prerequisites && ./configure --prefix=/opt/gcc-$GCC_VERSION/ --enable-languages=c,c++ && make && make install && echo 'PATH=/opt/gcc-$GCC_VERSION/bin:$PATH' >> ~/.bashrc && echo 'export CC=/opt/gcc-$GCC_VERSION/bin/gcc' >> ~/.bashrc && echo 'export CXX=/opt/gcc-$GCC_VERSION/bin/g++' >> ~/.bashrc

RUN echo 'JAVA_HOME="/usr/lib/jvm/open-jdk"' >> ~/.bashrc

RUN rm -rf $SOURCE_DIR
