/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_netty_tcnative_jni_ocsp_Native */

#ifndef _Included_io_netty_tcnative_jni_ocsp_Native
#define _Included_io_netty_tcnative_jni_ocsp_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_netty_tcnative_jni_ocsp_Native
 * Method:    newCallback
 * Signature: (JZLio/netty/tcnative/jni/ocsp/StatusCallback;)Lio/netty/tcnative/jni/ocsp/StatusCallback;
 */
JNIEXPORT jobject JNICALL Java_io_netty_tcnative_jni_ocsp_Native_newCallback
  (JNIEnv *, jclass, jlong, jboolean, jobject);

/*
 * Class:     io_netty_tcnative_jni_ocsp_Native
 * Method:    freeCallback
 * Signature: (JLio/netty/tcnative/jni/ocsp/StatusCallback;)V
 */
JNIEXPORT void JNICALL Java_io_netty_tcnative_jni_ocsp_Native_freeCallback
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_netty_tcnative_jni_ocsp_Native
 * Method:    setType
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_io_netty_tcnative_jni_ocsp_Native_setType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_netty_tcnative_jni_ocsp_Native
 * Method:    setResponse
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_io_netty_tcnative_jni_ocsp_Native_setResponse
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_netty_tcnative_jni_ocsp_Native
 * Method:    getResponse
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_netty_tcnative_jni_ocsp_Native_getResponse
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
